jobPortal/jobPortal/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings

from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    #url(r'^$', 'jobPortal.views.home', name='home'),
    #url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),

    url(r'^report/', include('report.urls')),
    url(r'^', include('portal.urls')),
    (r'^media/(?P<path>.*)$', 'django.views.static.serve',
        {'document_root': settings.MEDIA_ROOT}),
)

jobPortal/portal/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic import ListView
from portal.models import Advertisement

urlpatterns = patterns('portal.views',
    url(r'^$', 'home'),
    url(r'^about/$', 'about'),
    url(r'^add-advertisement/$', 'advertisement_register'),
    url(r'^add-resume/$', 'add_resume'),
    url(r'^account/change-password/$', 'change_password'),
    url(r'^special_ad_register/(?P<id>\d+)$', 'special_ad_register'),
    url(r'^account/$', 'page_acount_jobSeeker'),
    url(r'^faq/', 'faq'),
    url(r'^register/seeker/', 'register_seeker'),
    url(r'^register/employer/', 'register_employer'),
    url(r'^ads/$', 'advertisements'),
    url(r'^adss/$', 'advertisement'),
    url(r'^adss/request/', 'ad_request'),
    url(r'^resume/$', 'resume'),
    url(r'^resumes/$', 'resumes'),
    url(r'^resume/request/$', 'request_resume'),
    url(r'^festivals/$', 'festivals'),
    url(r'^festivals/register/$', 'register_festival'),
    url(r'^festivals/register/payment', 'festival_registered'),
    url(r'^ajax/account/history', 'account_history'),
    url(r'^search/$', 'search'),
    url(r'^account/evaluation/$', 'evaluation'),
    url(r'^updateSeeker/$', 'update_seeker'),
    url(r'^updateEmployer/$', 'update_employer'),
    url(r'^userResume/$', 'userResume'),
    url(r'^userAd/$', 'userAd'),
    url(r'^jobrequests/$', 'jobrequests'),
    url(r'^empJobrequests/$', 'employer_jobrequests'),
    url(r'^empJobproposal/$', 'employer_jobproposal'),
    url(r'^empAutomaticMatch/$', 'employer_automaticMatch'),
    url(r'^empSuccessfuls/$', 'employer_successfuls'),
    url(r'^jobproposal/$', 'jobproposal'),
    url(r'^automaticMatch/$', 'automaticMatch'),
    url(r'^successfuls/$', 'successfuls'),
    url(r'^forgotpass/$', 'forgot_password'),
    url(r'^resetpass', 'reset_password'),
    url(r'^account/contact_us/$', 'contact_us'),
    url(r'^updateResume/(?P<id>\d+)', 'update_resume'),
    url(r'^updateAd/(?P<id>\d+)', 'update_ad'),
    url(r'^resume/(?P<email>.+)', 'anotherUser_res'),
    url(r'^removeAd/(?P<id>\d+)', 'remove_ad'),
    url(r'^removeResume/(?P<id>\d+)', 'remove_res'),
    url(r'^accreq/(?P<id>\d+)', 'accept_request'),
    url(r'^rejreq/(?P<id>\d+)', 'reject_request'),
    url(r'^empaccreq/(?P<id>\d+)', 'emp_accept_request'),
    url(r'^emprejreq/(?P<id>\d+)', 'emp_reject_request'),

    
    

    
    
    

    
    
    

)

urlpatterns += patterns('',
    url(r'^login/$', 'django.contrib.auth.views.login', {'template_name': 'login.html'}),
    url(r'^logout/$', 'django.contrib.auth.views.logout'),
)
urlpatterns += patterns('',
    url(r'^ads/bysalary$', ListView.as_view(
    queryset=Advertisement.objects.all().order_by('-salary'),
    context_object_name='ads',
    template_name='advertisements.html', 
    )),
    url(r'^ads/bydate$', ListView.as_view(
    queryset=Advertisement.objects.all().order_by('-date'),
    context_object_name='ads',
    template_name='advertisements.html', 
    )),
)

jobPortal/report/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns('report.views',
    url(r'^$', 'payments'),
    url(r'^seekers/$', 'seekers'),
    url(r'^employers/$', 'employers'),
    url(r'^comments/$', 'comments'),
    url(r'^success/$', 'success'),
    url(r'^verify/$', 'verify'),
    url(r'^ajax/$', 'ajax'),
)

jobPortal/portal/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.models import User as djangoUser
from os import urandom
import datetime
from django.utils import timezone
from base64 import urlsafe_b64encode
from os.path import splitext


GENDER_CHOICES = (
    ('F', _("female")),
    ('M', _("male")),
)
STATE_CHOICES = (
    ('A', _('Active')),
    ('D', _('Deactive')),
)
CATEGORY_STATE = (
    ('SE', _("Software engineer")),
    ('ME', _("Mechanical engineer"))
)
CITY_CHOICES = (
    ('T', _('Tehran')),
    ('E', _('Esfahan')),
    ('M', _('Mashhad')),
    ('S', _('Semnan')),
    ('A', _('Arak')),
)

def sluggenerator():
    return random_generator(20) 

random_generator = lambda random_size: urlsafe_b64encode(urandom(random_size))
def get_random_filename_generator(fn_format, default_extension='.jpg', random_size=12):
    """Returns a random filename generator suitable for upload_to of django FileField"""

    def random_filename(instance, filename):
        split = splitext(filename)
        extension = split[-1] if len(split) > 1 else default_extension
        return fn_format % (random_generator(random_size), extension)

    return random_filename
    
def sluggenerator():
    return random_generator(20) 
    
class User(models.Model):
    user = models.ForeignKey(djangoUser)
    name = models.CharField(verbose_name=_("Full name"), max_length=250,
            help_text=_("This name should be identical to the name of the owner of the back account for future payments"))
    telephone = models.CharField(verbose_name=_("Telephone number"), max_length=15, blank=True)
    mobilephone = models.CharField(verbose_name=_("Mobile phone number"), max_length=15, blank=True)
    address = models.TextField(verbose_name=_("Contact address"))
    postal_code = models.CharField(verbose_name=_("Postal code"),
            max_length=10, blank=True)
    email = models.EmailField(verbose_name=_("Email"))
    payment = models.OneToOneField("Payment", verbose_name=_("Payment"), null=True, blank=True)
    register_date = models.DateField(_("Registration date"), default=datetime.date.today)

    class Meta:
        verbose_name = _('account')
        verbose_name_plural = _('accounts')
    def __unicode__(self):
        return "%s" %self.name




class JobSeeker(User):
    national_code = models.CharField(verbose_name=_("National code"),
            max_length=10)
    date_of_birth = models.DateField(verbose_name=_("Date of birth"))
    gender = models.CharField(verbose_name=_("Gender"), max_length=1,
                                         default='M', choices=GENDER_CHOICES)
    class Meta:
        verbose_name = _('job seeker')
        verbose_name_plural = _('job seekers')


class Employer(User):
    economic_code = models.CharField(verbose_name=_("Economic code"),
            max_length=12)
    registration_number = models.CharField(verbose_name=_("Registration number"),
            max_length=10)
    VERIFICATION_STATE_CHOICES = (
        ('N', _("not reviewed")),

        ('A', _("verified")),
        ('M', _("modified - was verified")),

        ('D', _("defective")),
        ('F', _("modified - was defective")),
    )
    verified_by_human = models.CharField(verbose_name=_("Reviewed by Human"), max_length=1,
                                         default='N', choices=VERIFICATION_STATE_CHOICES)

    class Meta:
        verbose_name = _('employer')
        verbose_name_plural = _('employers')
   


class Resume(models.Model):
    job_experiences = models.TextField(verbose_name=_("Job experiences"))
    EDUCATION_CHOICES = (
        ('DI', _('Diploma')),
        ('BS', _('Bachelor of Science')),
        ('MS', _('Master of Science')),
        ('PH', _('PHD')),
        ('PD', _('Post Doc')),
    )
    city = models.CharField(_("City"), max_length=1, default='T', choices=CITY_CHOICES)
    education = models.CharField(verbose_name=_("Education"),max_length=2, default='DI', choices=EDUCATION_CHOICES)
    skills = models.TextField(verbose_name=_("Skills"))
    state = models.CharField(_("state"), max_length=1, default='A', choices=STATE_CHOICES)
    job_seeker = models.ForeignKey(JobSeeker, verbose_name=_("Job seeker"), db_index=True)
    category = models.CharField(_("Category"), max_length=2, default='S', choices=CATEGORY_STATE)
    additional_informatiom = models.TextField(null=True,blank =True)
    profile_pic=models.FileField(_("Profile picture"), upload_to=get_random_filename_generator("photos/%s%s"), null = True ,blank=True)

    class Meta:
        verbose_name = _('resume')
        verbose_name_plural = _('resumes')
    def __unicode__(self):
        return "%s" %self.job_seeker.name



class Advertisement(models.Model):
    city = models.CharField(_("City"), max_length=1, default='T', choices=CITY_CHOICES)
    salary = models.PositiveIntegerField(_("Salary"), default=0, help_text=_("Tomans"))
    GENDER_CHOICES_BOTH = (
        ('F', _('female')),
        ('M', _('male')),
        ('B', _('both')),
    )
    gender = models.CharField(verbose_name=_("Gender"), max_length=1,
                                         default='B', choices=GENDER_CHOICES_BOTH)
    age = models.IntegerField(_("Age"), default=18)
    number_of_people = models.IntegerField(_("Number of required people"), default=1)
    state = models.CharField(_("state"), max_length=1, default='A', choices=STATE_CHOICES)
    required_skills = models.TextField(_("Required skills"))
    work_hours = models.IntegerField(_("Work hours"), default=8)
    addres = models.TextField(_("Address"))
    category = models.CharField(_("Category"), max_length=2, default='S', choices=CATEGORY_STATE)
    employer = models.ForeignKey(Employer, null = True)
    date = models.DateTimeField(_("Date"),default=timezone.now)
    logo = models.FileField(_("Logo"), upload_to=get_random_filename_generator("photos/%s%s"), null = True )

    EDUCATION_CHOICES = (
        ('DI', _('Diploma')),
        ('BS', _('Bachelor of Science')),
        ('MS', _('Master of Science')),
        ('PH', _('PHD')),
        ('PD', _('Post Doc')),
    )
    education = models.CharField(verbose_name=_("Education"),max_length=2, default='DI', choices=EDUCATION_CHOICES)

    class Meta:
        verbose_name = _('advertisement')
        verbose_name_plural = _('advertisements')
    def __unicode__(self):
        return "%s" %self.employer.name


class SpecialAdvertisement(models.Model):
    advertisement = models.ForeignKey(Advertisement, verbose_name=_("Advertisement"))
    from_date = models.DateField(_("From date"), default=datetime.date.today)
    to_date = models.DateField(_("To date"), default=datetime.date.today)
    payment = models.OneToOneField("Payment", verbose_name=_("Payment"), null=True)

    class Meta:
        verbose_name = _('special advertisement')
        verbose_name_plural = _('special advertisements')



class Festival(models.Model):
    from_date = models.DateTimeField(_("From date"))
    to_date = models.DateTimeField(_("To date"))
    title = models.CharField(_("Title"), max_length=50)
    description = models.TextField(_("Description"))
    poster = models.FileField(upload_to=get_random_filename_generator("photos/%s%s"), null = True )
    discount = models.PositiveIntegerField(_("Discount"),default=0)
    price = models.PositiveIntegerField(_("Price"),default=0, help_text=_("Tomans"))


    class Meta:
        verbose_name = _('festival')
        verbose_name_plural = _('festivals')
    def __unicode__(self):
        return "%s" %self.title



class Payment(models.Model):
    amount = models.PositiveIntegerField(_("Amount"), default=0, help_text=_("Tomans"))
    refrence_code = models.CharField(_("Refrence code"), max_length=30,default= sluggenerator)

    class Meta:
        verbose_name = _('payment')
        verbose_name_plural = _('payments')
    def __unicode__(self):
        return "%s" %self.refrence_code


class RegisterFestival(models.Model):
    employer = models.ForeignKey(Employer)
    festival = models.ForeignKey(Festival)
    payment = models.ForeignKey(Payment)
    

    class Meta:
        verbose_name = _('register festival')
        verbose_name_plural = _('register festivals')
    def __unicode__(self):
        return "%s" %self.festival.title + "_" + self.employer.name


class JobRequest(models.Model):
    # resume = models.ForeignKey(Resume)
    advertisement = models.ForeignKey(Advertisement)
    job_seeker = models.ForeignKey(JobSeeker)
    SUCCESS_CHOICES = (
        ('F', _('False')),
        ('T', _('True')),
        ('P', _('Pending'))
    )

    success = models.CharField(_("Success"), default='P', blank=True, choices =SUCCESS_CHOICES, max_length = 1)
    DIRECTION_CHOICES = (
        ('S', _('Job seeker')),
        ('E', _('Employer')),
        ('Y', _('System')),
    )
    direction = models.CharField(_("Direction"), choices=DIRECTION_CHOICES, max_length=1)
    hide_seeker = models.BooleanField(_("Hide_job_seeker"), default = False)
    hide_employer = models.BooleanField(_("Hide_employer"),default = False)

    class Meta:
        verbose_name = _('job request')
        verbose_name_plural = _('job requests')
    def __unicode__(self):
        return "%s" %self.advertisement.employer.name+"_"+self.job_seeker.name


class Comment(models.Model):
    
    text = models.TextField(_("Text"))
    KIND_CHOICES = (
        ('S', _('Suggest')),
        ('C', _('Critic')),
    )
    kind = models.CharField(_("Kind"), choices=KIND_CHOICES, max_length=1)
    user = models.ForeignKey(User)
    register_date = models.DateField(_("Registration date"), default=datetime.date.today)

    class Meta:
        verbose_name = _('comment')
        verbose_name_plural = _('comments')
    def ___unicode___(self):
        return "%s" %self.kind


class AdComment(models.Model):
    
    text = models.TextField(_("Text"))
    advertisement = models.ForeignKey(Advertisement, null = True)

jobPortal/report/views.py
import datetime
from json import dumps

from django.http import HttpResponse
from django.contrib.admin.views.decorators import staff_member_required
from django.shortcuts import render
from django.db.models import Sum, Count

from portal.models import Payment, JobSeeker, Employer, Comment, JobRequest

@staff_member_required
def payments(request):
    dates = []
    sales = []
    now = datetime.date.today()
    for i in range(14,0,-1):
        time = now - datetime.timedelta(days=i)
        dates.append(time.strftime('%d %b'))
        total = Payment.objects.filter(specialadvertisement__from_date=time).aggregate(Sum('amount'))
        total = total.get('amount__sum', 0) or 0
        sales.append(total/1000)
    payments = Payment.objects.select_related('specialadvertisement')
    return render(request, "payments.html", {'dates': dates, 'sales': sales, 'payments': payments})

@staff_member_required
def seekers(request):
    dates = []
    registers = []
    now = datetime.date.today()
    for i in range(14,0,-1):
        time = now - datetime.timedelta(days=i)
        dates.append(time.strftime('%d %b'))
        total = JobSeeker.objects.filter(register_date=time).aggregate(Count('id'))
        total = total.get('id__count', 0) or 0
        registers.append(total)
    seeker = JobSeeker.objects.order_by('register_date')[:100]
    return render(request, "seekers.html", {'dates': dates, 'registers': registers, 'seekers': seeker})

@staff_member_required
def employers(request):
    dates = []
    registers = []
    now = datetime.date.today()
    for i in range(14,0,-1):
        time = now - datetime.timedelta(days=i)
        dates.append(time.strftime('%d %b'))
        total = Employer.objects.filter(register_date=time).aggregate(Count('id'))
        total = total.get('id__count', 0) or 0
        registers.append(total)
    employer = Employer.objects.order_by('register_date')[:100]
    return render(request, "employers.html", {'dates': dates, 'registers': registers, 'employers': employer})

@staff_member_required
def comments(request):
    comment = Comment.objects.order_by('register_date')[:100]
    return render(request, "comments.html", {'comments': comment})

@staff_member_required
def success(request):
    requests = JobRequest.objects.filter(success='T').order_by('id')[:100]
    return render(request, "success.html", {'requests': requests})

@staff_member_required
def verify(request):
    employers = Employer.objects.filter(verified_by_human='N')
    return render(request, "verify.html", {'employers': employers})

@staff_member_required
def ajax(request):
    id_e = request.GET.get('id', None)
    state = request.GET.get('state', None)
    emp = Employer.objects.get(id=id_e)
    if state == 'V':
        emp.verified_by_human = 'A'
    else:
        emp.verified_by_human = 'D'
    emp.save()
    return HttpResponse(dumps({'error':0}),content_type ='application/json')

jobPortal/report/templates/comments.html
{% extends "report_base.html" %}

{% block content %}
<table class="table table-bordered table-striped">
	<thead>
		<tr>
			<th>#</th>
			<th>نوع نظر</th>
			<th>نام کاربر</th>
			<th>تاریخ ثبت نظر</th>
			<th>نظر</th>
		</tr>
	</thead>
	<tbody>
	{% for c in comments %}
		<tr class="{% if c.kind == 'S' %}success{% else %}danger{% endif %}">
			<td>{{ forloop.counter }}</td>
			<td>{{ c.get_kind_display }}</td>
			<td>{{ c.user.name }}</td>
			<td>{{ c.register_date }}</td>
			<td>{{ c.text|safe }}</td>
		</tr>
	{% endfor %}
	</tbody>
</table>
{% endblock %}

jobPortal/report/templates/employers.html
{% extends "report_base.html" %}

{% block content %}
<div class="well container-fluid" id="chart_container" style="width: 95%; height: 300px; direction: ltr">
</div>
<table class="table table-bordered table-striped">
          <thead>
            <tr>
              <th>#</th>
              <th>نام</th>
              <th>تاریخ ثبت‌نام</th>
            </tr>
          </thead>
          <tbody>
          {% for e in employers %}
            <tr>
              <td>{{ forloop.counter }}</td>
              <td>{{ e.name }}</td>
              <td>{{ e.register_date }}</td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
<script src="{{STATIC_URL}}js/highcharts.js"></script>
<script type="text/javascript">
$(function () {
	var chart;
	$(document).ready(function() {
		chart = new Highcharts.Chart({
			chart: {
				renderTo: 'chart_container',
				type: 'line'
			},

			title: {
				text: 'نمودار ثبت‌نام در دو هفته اخیر'
			},

			xAxis: {
				title: {
					text: 'روز'
				},
				categories:[
					{% for date in dates %}
						{% if forloop.counter != 1 %},{%endif%}
						"{{ date }}"
					{% endfor %}
				],
				minTickInterval : 2
			},

			yAxis: {
				title: {
					text: 'تعداد'
				},
				min: 0
			},
			legend: {
				enabled: false
			},
			series: [{
				name: 'ثبت‌نام‌ها',
				data: [
					{% for r in registers %}
						{% if forloop.counter != 1 %},{%endif%} {{r}}
					{% endfor %}
				],
			}]
		});
	});
});
</script>
{% endblock %}

jobPortal/report/templates/payments.html
{% extends "report_base.html" %}

{% block content %}
<div class="well container-fluid" id="chart_container" style="width: 95%; height: 300px; direction: ltr">
</div>
<table class="table table-bordered table-striped">
          <thead>
            <tr>
              <th>#</th>
              <th>آگهی</th>
              <th>تاریخ</th>
              <th>مقدار</th>
              <th>شماره فاکتور</th>
            </tr>
          </thead>
          <tbody>
          {% for p in payments %}
            <tr>
              <td>{{ forloop.counter }}</td>
              <td>{{ p.specialadvertisement.advertisement.employer.name }}</td>
              <td>{{ p.specialadvertisement.from_date }}</td>
              <td>{{ p.amount }}</td>
              <td>{{ p.refrence_code }}</td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
<script src="{{STATIC_URL}}js/highcharts.js"></script>
<script type="text/javascript">
$(function () {
	var chart;
	$(document).ready(function() {
		chart = new Highcharts.Chart({
			chart: {
				renderTo: 'chart_container',
				type: 'line'
			},

			title: {
				text: 'نمودار فروش در دو هفته اخیر'
			},

			xAxis: {
				title: {
					text: 'روز'
				},
				categories:[
					{% for date in dates %}
						{% if forloop.counter != 1 %},{%endif%}
						"{{ date }}"
					{% endfor %}
				],
				minTickInterval : 2
			},

			yAxis: {
				title: {
					text: 'مقدار فروش- ۱۰۰۰ ریال'
				},
				min: 0
			},
			legend: {
				enabled: false
			},
			series: [{
				name: 'فروش‌ها',
				data: [
					{% for sale in sales %}
						{% if forloop.counter != 1 %},{%endif%} {{sale}}
					{% endfor %}
				],
			}]
		});
	});
});
</script>
{% endblock %}

jobPortal/report/templates/report_base.html
<!DOCTYPE html>
<html lang="en">
  <head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta name="description" content="">
	<meta name="author" content="">

	<title>درگاه کاریابی شریف</title>

	<!-- Bootstrap core CSS -->
	<link href="{{STATIC_URL}}css/bootstrap.css" rel="stylesheet">

	<!-- Add custom CSS here -->
	<link href="{{STATIC_URL}}css/modern-business.css" rel="stylesheet">
	<link href="{{STATIC_URL}}font-awesome/css/font-awesome.min.css" rel="stylesheet">

	<!-- JavaScript -->
	<script src="{{STATIC_URL}}js/jquery-1.10.2.js"></script>
	<script src="{{STATIC_URL}}js/bootstrap.js"></script>
	<script src="{{STATIC_URL}}js/modern-business.js"></script>

  </head>

<body dir="rtl">
<!--     <style>
	.navbar.transparent.navbar-inverse .navbar-inner {
	   background: rgba(0,0,0,0.4);
	}
	</style> -->

	<nav class="navbar navbar-inverse navbar-fixed-top transparent" style="background: rgba(0,0,0,0.7)" role="navigation">

	  <div class="container">
		<div class="navbar-header pull-left">
		  <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse"></button>
		  <!-- You'll want to use a responsive image option so this logo looks good on devices - I recommend using something like retina.js (do a quick Google search for it and you'll find it) -->
		  <a class="navbar-brand" href="/">درگاه کاریابی شریف</a>
		</div>
	  </div><!-- /.container -->
	</nav>
	<style>
	.navbar-inverse {
	border-color:transparent;
	}
	</style>
    <div class="container">
 
    <div class="row">
      <div class="col-md-3 col-sm-4 sidebar">
    	  <ul class="nav nav-stacked nav-pills">
    		<li class="{% ifequal request.META.PATH_INFO '/report/' %}active{% endifequal %}"><a href="/report/">گزارش پرداخت‌ها</a></li>	
    		<li class="{% ifequal request.META.PATH_INFO '/report/seekers/' %}active{% endifequal %}"><a href="/report/seekers/">گزارش کارجویان ثبت‌نامی</a></li>
    		<li class="{% ifequal request.META.PATH_INFO '/report/employers/' %}active{% endifequal %}"><a href="/report/employers/">گزارش کارفرمایان ثبت‌نامی</a></li>
    		<li class="{% ifequal request.META.PATH_INFO '/report/comments/' %}active{% endifequal %}"><a href="/report/comments/">گزارش نظرات</a></li>
			<li class="{% ifequal request.META.PATH_INFO '/report/success/' %}active{% endifequal %}"><a href="/report/success/">گزارش کاریابی‌های موفق</a></li>
			<li class="{% ifequal request.META.PATH_INFO '/report/verify/' %}active{% endifequal %}"><a href="/report/verify/">تایید/رد کارفرمایان</a></li>
    	  </ul>
      </div>
    
      	<div class="col-md-9 col-sm-8 sidebar">
			<div class="well container-fluid">
   	   	{% block content %}
   	   	{% endblock %}
	</div>

   	</div>
          
   	</div><!-- /.row -->
	 
   </div><!-- /.container -->
	
	<div class="container">
	
		  <hr>
	
		  <footer>
			<div class="row">
			  <div class="col-lg-12">
				<center><p>Copyright &copy; TARA 2013</p>
				<p>تمامی حقوق این درگاه متعلق به شرکت تارا است.</p></center>
			  </div>
			</div>
		  </footer>
	
		</div><!-- /.container -->
		
  </body>
  </html>

jobPortal/report/templates/seekers.html
{% extends "report_base.html" %}

{% block content %}
<div class="well container-fluid" id="chart_container" style="width: 95%; height: 300px; direction: ltr">
</div>
<table class="table table-bordered table-striped">
          <thead>
            <tr>
              <th>#</th>
              <th>نام</th>
              <th>تاریخ ثبت‌نام</th>
            </tr>
          </thead>
          <tbody>
          {% for s in seekers %}
            <tr>
              <td>{{ forloop.counter }}</td>
              <td>{{ s.name }}</td>
              <td>{{ s.register_date }}</td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
<script src="{{STATIC_URL}}js/highcharts.js"></script>
<script type="text/javascript">
$(function () {
	var chart;
	$(document).ready(function() {
		chart = new Highcharts.Chart({
			chart: {
				renderTo: 'chart_container',
				type: 'line'
			},

			title: {
				text: 'نمودار ثبت‌نام در دو هفته اخیر'
			},

			xAxis: {
				title: {
					text: 'روز'
				},
				categories:[
					{% for date in dates %}
						{% if forloop.counter != 1 %},{%endif%}
						"{{ date }}"
					{% endfor %}
				],
				minTickInterval : 2
			},

			yAxis: {
				title: {
					text: 'تعداد'
				},
				min: 0
			},
			legend: {
				enabled: false
			},
			series: [{
				name: 'ثبت‌نام‌ها',
				data: [
					{% for r in registers %}
						{% if forloop.counter != 1 %},{%endif%} {{r}}
					{% endfor %}
				],
			}]
		});
	});
});
</script>
{% endblock %}

jobPortal/report/templates/success.html
{% extends "report_base.html" %}

{% block content %}
<table class="table table-bordered table-striped">
	<thead>
		<tr>
			<th>#</th>
			<th>آگهی</th>
			<th>کارجو</th>
			<th>جهت</th>
		</tr>
	</thead>
	<tbody>
	{% for r in requests %}
		<tr>
			<td>{{ forloop.counter }}</td>
			<td>{{ r.advertisement.employer.name }}</td>
			<td>{{ r.job_seeker.name }}</td>
			<td>{{ r.get_direction_display }}</td>
		</tr>
	{% endfor %}
	</tbody>
</table>
{% endblock %}

jobPortal/report/templates/verify.html
{% extends "report_base.html" %}

{% block content %}
<table class="table table-striped">
	<thead>
		<tr>
			<th>#</th>
			<th>نام</th>
			<th>کد اقتصادی</th>
			<th>شماره ثبت</th>
			<th>تایید/رد</th>
		</tr>
	</thead>
	<tbody>
	{% for e in employers %}
		<tr id="{{ e.id }}">
			<td>{{ forloop.counter }}</td>
			<td>{{ e.name }}</td>
			<td>{{ e.economic_code }}</td>
			<td>{{ e.registration_number }}</td>
			<td><button class="btn btn-primary" onclick="verify({{ e.id }}, 'V')">تایید</button><button class="btn btn-danger"  onclick="verify({{ e.id }}, 'R')">رد</button></td>
		</tr>
	{% endfor %}
	</tbody>
</table>
<script>

function verify(id, state){
	$.ajax({
		url: '/report/ajax/',
		type: 'get',
		dataType: 'json',
		data: { 'id' : id, 'state': state},
		success: function(data, status, xhr){
			if (data.error){
			   // Request error
			   console.log(data.error);
			}else {
				console.log('dasgare');
			}

		},
	});
	$('#'+id).hide()
}

</script>
{% endblock %}