jobPortal/jobPortal/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings

from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    #url(r'^$', 'jobPortal.views.home', name='home'),
    #url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),

    url(r'^report/', include('report.urls')),
    url(r'^', include('portal.urls')),
    (r'^media/(?P<path>.*)$', 'django.views.static.serve',
        {'document_root': settings.MEDIA_ROOT}),
)

jobPortal/portal/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic import ListView
from portal.models import Advertisement

urlpatterns = patterns('portal.views',
    url(r'^$', 'home'),
    url(r'^about/$', 'about'),
    url(r'^add-advertisement/$', 'advertisement_register'),
    url(r'^add-resume/$', 'add_resume'),
    url(r'^account/change-password/$', 'change_password'),
    url(r'^special_ad_register/(?P<id>\d+)$', 'special_ad_register'),
    url(r'^account/$', 'page_acount_jobSeeker'),
    url(r'^faq/', 'faq'),
    url(r'^register/seeker/', 'register_seeker'),
    url(r'^register/employer/', 'register_employer'),
    url(r'^ads/$', 'advertisements'),
    url(r'^adss/$', 'advertisement'),
    url(r'^adss/request/', 'ad_request'),
    url(r'^resume/$', 'resume'),
    url(r'^resumes/$', 'resumes'),
    url(r'^resume/request/$', 'request_resume'),
    url(r'^festivals/$', 'festivals'),
    url(r'^festivals/register/$', 'register_festival'),
    url(r'^festivals/register/payment', 'festival_registered'),
    url(r'^ajax/account/history', 'account_history'),
    url(r'^search/$', 'search'),
    url(r'^account/evaluation/$', 'evaluation'),
    url(r'^updateSeeker/$', 'update_seeker'),
    url(r'^updateEmployer/$', 'update_employer'),
    url(r'^userResume/$', 'userResume'),
    url(r'^userAd/$', 'userAd'),
    url(r'^jobrequests/$', 'jobrequests'),
    url(r'^empJobrequests/$', 'employer_jobrequests'),
    url(r'^empJobproposal/$', 'employer_jobproposal'),
    url(r'^empAutomaticMatch/$', 'employer_automaticMatch'),
    url(r'^empSuccessfuls/$', 'employer_successfuls'),
    url(r'^jobproposal/$', 'jobproposal'),
    url(r'^automaticMatch/$', 'automaticMatch'),
    url(r'^successfuls/$', 'successfuls'),
    url(r'^forgotpass/$', 'forgot_password'),
    url(r'^resetpass', 'reset_password'),
    url(r'^account/contact_us/$', 'contact_us'),
    url(r'^updateResume/(?P<id>\d+)', 'update_resume'),
    url(r'^updateAd/(?P<id>\d+)', 'update_ad'),
    url(r'^resume/(?P<email>.+)', 'anotherUser_res'),
    url(r'^removeAd/(?P<id>\d+)', 'remove_ad'),
    url(r'^removeResume/(?P<id>\d+)', 'remove_res'),
    url(r'^accreq/(?P<id>\d+)', 'accept_request'),
    url(r'^rejreq/(?P<id>\d+)', 'reject_request'),
    url(r'^empaccreq/(?P<id>\d+)', 'emp_accept_request'),
    url(r'^emprejreq/(?P<id>\d+)', 'emp_reject_request'),

    
    

    
    
    

    
    
    

)

urlpatterns += patterns('',
    url(r'^login/$', 'django.contrib.auth.views.login', {'template_name': 'login.html'}),
    url(r'^logout/$', 'django.contrib.auth.views.logout'),
)
urlpatterns += patterns('',
    url(r'^ads/bysalary$', ListView.as_view(
    queryset=Advertisement.objects.all().order_by('-salary'),
    context_object_name='ads',
    template_name='advertisements.html', 
    )),
    url(r'^ads/bydate$', ListView.as_view(
    queryset=Advertisement.objects.all().order_by('-date'),
    context_object_name='ads',
    template_name='advertisements.html', 
    )),
)

jobPortal/portal/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.models import User as djangoUser
from os import urandom
import datetime
from django.utils import timezone
from base64 import urlsafe_b64encode
from os.path import splitext


GENDER_CHOICES = (
    ('F', _("female")),
    ('M', _("male")),
)
STATE_CHOICES = (
    ('A', _('Active')),
    ('D', _('Deactive')),
)
CATEGORY_STATE = (
    ('SE', _("Software engineer")),
    ('ME', _("Mechanical engineer"))
)
CITY_CHOICES = (
    ('T', _('Tehran')),
    ('E', _('Esfahan')),
    ('M', _('Mashhad')),
    ('S', _('Semnan')),
    ('A', _('Arak')),
)

def sluggenerator():
    return random_generator(20) 

random_generator = lambda random_size: urlsafe_b64encode(urandom(random_size))
def get_random_filename_generator(fn_format, default_extension='.jpg', random_size=12):
    """Returns a random filename generator suitable for upload_to of django FileField"""

    def random_filename(instance, filename):
        split = splitext(filename)
        extension = split[-1] if len(split) > 1 else default_extension
        return fn_format % (random_generator(random_size), extension)

    return random_filename
    
def sluggenerator():
    return random_generator(20) 
    
class User(models.Model):
    user = models.ForeignKey(djangoUser)
    name = models.CharField(verbose_name=_("Full name"), max_length=250,
            help_text=_("This name should be identical to the name of the owner of the back account for future payments"))
    telephone = models.CharField(verbose_name=_("Telephone number"), max_length=15, blank=True)
    mobilephone = models.CharField(verbose_name=_("Mobile phone number"), max_length=15, blank=True)
    address = models.TextField(verbose_name=_("Contact address"))
    postal_code = models.CharField(verbose_name=_("Postal code"),
            max_length=10, blank=True)
    email = models.EmailField(verbose_name=_("Email"))
    payment = models.OneToOneField("Payment", verbose_name=_("Payment"), null=True, blank=True)
    register_date = models.DateField(_("Registration date"), default=datetime.date.today)

    class Meta:
        verbose_name = _('account')
        verbose_name_plural = _('accounts')
    def __unicode__(self):
        return "%s" %self.name




class JobSeeker(User):
    national_code = models.CharField(verbose_name=_("National code"),
            max_length=10)
    date_of_birth = models.DateField(verbose_name=_("Date of birth"))
    gender = models.CharField(verbose_name=_("Gender"), max_length=1,
                                         default='M', choices=GENDER_CHOICES)
    class Meta:
        verbose_name = _('job seeker')
        verbose_name_plural = _('job seekers')


class Employer(User):
    economic_code = models.CharField(verbose_name=_("Economic code"),
            max_length=12)
    registration_number = models.CharField(verbose_name=_("Registration number"),
            max_length=10)
    VERIFICATION_STATE_CHOICES = (
        ('N', _("not reviewed")),

        ('A', _("verified")),
        ('M', _("modified - was verified")),

        ('D', _("defective")),
        ('F', _("modified - was defective")),
    )
    verified_by_human = models.CharField(verbose_name=_("Reviewed by Human"), max_length=1,
                                         default='N', choices=VERIFICATION_STATE_CHOICES)

    class Meta:
        verbose_name = _('employer')
        verbose_name_plural = _('employers')
   


class Resume(models.Model):
    job_experiences = models.TextField(verbose_name=_("Job experiences"))
    EDUCATION_CHOICES = (
        ('DI', _('Diploma')),
        ('BS', _('Bachelor of Science')),
        ('MS', _('Master of Science')),
        ('PH', _('PHD')),
        ('PD', _('Post Doc')),
    )
    city = models.CharField(_("City"), max_length=1, default='T', choices=CITY_CHOICES)
    education = models.CharField(verbose_name=_("Education"),max_length=2, default='DI', choices=EDUCATION_CHOICES)
    skills = models.TextField(verbose_name=_("Skills"))
    state = models.CharField(_("state"), max_length=1, default='A', choices=STATE_CHOICES)
    job_seeker = models.ForeignKey(JobSeeker, verbose_name=_("Job seeker"), db_index=True)
    category = models.CharField(_("Category"), max_length=2, default='S', choices=CATEGORY_STATE)
    additional_informatiom = models.TextField(null=True,blank =True)
    profile_pic=models.FileField(_("Profile picture"), upload_to=get_random_filename_generator("photos/%s%s"), null = True ,blank=True)

    class Meta:
        verbose_name = _('resume')
        verbose_name_plural = _('resumes')
    def __unicode__(self):
        return "%s" %self.job_seeker.name



class Advertisement(models.Model):
    city = models.CharField(_("City"), max_length=1, default='T', choices=CITY_CHOICES)
    salary = models.PositiveIntegerField(_("Salary"), default=0, help_text=_("Tomans"))
    GENDER_CHOICES_BOTH = (
        ('F', _('female')),
        ('M', _('male')),
        ('B', _('both')),
    )
    gender = models.CharField(verbose_name=_("Gender"), max_length=1,
                                         default='B', choices=GENDER_CHOICES_BOTH)
    age = models.IntegerField(_("Age"), default=18)
    number_of_people = models.IntegerField(_("Number of required people"), default=1)
    state = models.CharField(_("state"), max_length=1, default='A', choices=STATE_CHOICES)
    required_skills = models.TextField(_("Required skills"))
    work_hours = models.IntegerField(_("Work hours"), default=8)
    addres = models.TextField(_("Address"))
    category = models.CharField(_("Category"), max_length=2, default='S', choices=CATEGORY_STATE)
    employer = models.ForeignKey(Employer, null = True)
    date = models.DateTimeField(_("Date"),default=timezone.now)
    logo = models.FileField(_("Logo"), upload_to=get_random_filename_generator("photos/%s%s"), null = True )

    EDUCATION_CHOICES = (
        ('DI', _('Diploma')),
        ('BS', _('Bachelor of Science')),
        ('MS', _('Master of Science')),
        ('PH', _('PHD')),
        ('PD', _('Post Doc')),
    )
    education = models.CharField(verbose_name=_("Education"),max_length=2, default='DI', choices=EDUCATION_CHOICES)

    class Meta:
        verbose_name = _('advertisement')
        verbose_name_plural = _('advertisements')
    def __unicode__(self):
        return "%s" %self.employer.name


class SpecialAdvertisement(models.Model):
    advertisement = models.ForeignKey(Advertisement, verbose_name=_("Advertisement"))
    from_date = models.DateField(_("From date"), default=datetime.date.today)
    to_date = models.DateField(_("To date"), default=datetime.date.today)
    payment = models.OneToOneField("Payment", verbose_name=_("Payment"), null=True)

    class Meta:
        verbose_name = _('special advertisement')
        verbose_name_plural = _('special advertisements')



class Festival(models.Model):
    from_date = models.DateTimeField(_("From date"))
    to_date = models.DateTimeField(_("To date"))
    title = models.CharField(_("Title"), max_length=50)
    description = models.TextField(_("Description"))
    poster = models.FileField(upload_to=get_random_filename_generator("photos/%s%s"), null = True )
    discount = models.PositiveIntegerField(_("Discount"),default=0)
    price = models.PositiveIntegerField(_("Price"),default=0, help_text=_("Tomans"))


    class Meta:
        verbose_name = _('festival')
        verbose_name_plural = _('festivals')
    def __unicode__(self):
        return "%s" %self.title



class Payment(models.Model):
    amount = models.PositiveIntegerField(_("Amount"), default=0, help_text=_("Tomans"))
    refrence_code = models.CharField(_("Refrence code"), max_length=30,default= sluggenerator)

    class Meta:
        verbose_name = _('payment')
        verbose_name_plural = _('payments')
    def __unicode__(self):
        return "%s" %self.refrence_code


class RegisterFestival(models.Model):
    employer = models.ForeignKey(Employer)
    festival = models.ForeignKey(Festival)
    payment = models.ForeignKey(Payment)
    

    class Meta:
        verbose_name = _('register festival')
        verbose_name_plural = _('register festivals')
    def __unicode__(self):
        return "%s" %self.festival.title + "_" + self.employer.name


class JobRequest(models.Model):
    # resume = models.ForeignKey(Resume)
    advertisement = models.ForeignKey(Advertisement)
    job_seeker = models.ForeignKey(JobSeeker)
    SUCCESS_CHOICES = (
        ('F', _('False')),
        ('T', _('True')),
        ('P', _('Pending'))
    )

    success = models.CharField(_("Success"), default='P', blank=True, choices =SUCCESS_CHOICES, max_length = 1)
    DIRECTION_CHOICES = (
        ('S', _('Job seeker')),
        ('E', _('Employer')),
        ('Y', _('System')),
    )
    direction = models.CharField(_("Direction"), choices=DIRECTION_CHOICES, max_length=1)
    hide_seeker = models.BooleanField(_("Hide_job_seeker"), default = False)
    hide_employer = models.BooleanField(_("Hide_employer"),default = False)

    class Meta:
        verbose_name = _('job request')
        verbose_name_plural = _('job requests')
    def __unicode__(self):
        return "%s" %self.advertisement.employer.name+"_"+self.job_seeker.name


class Comment(models.Model):
    
    text = models.TextField(_("Text"))
    KIND_CHOICES = (
        ('S', _('Suggest')),
        ('C', _('Critic')),
    )
    kind = models.CharField(_("Kind"), choices=KIND_CHOICES, max_length=1)
    user = models.ForeignKey(User)
    register_date = models.DateField(_("Registration date"), default=datetime.date.today)

    class Meta:
        verbose_name = _('comment')
        verbose_name_plural = _('comments')
    def ___unicode___(self):
        return "%s" %self.kind


class AdComment(models.Model):
    
    text = models.TextField(_("Text"))
    advertisement = models.ForeignKey(Advertisement, null = True)

jobPortal/portal/templates/advertisements.html
{% extends 'base.html' %}
{% block content%}
<div class="container">

  <div class="row">

	<div class="col-lg-12">
	  <h1 class="page-header">آگهی های ثبت شده<small> </small></h1>
	  <ol class="breadcrumb">
		  <li class="dropdown">
						<span class="dropdown-toggle" data-toggle="dropdown">نمایش بر اساس <b class="caret"></b></span>
						<ul class="dropdown-menu">
						  <li><a href="/ads/bydate">زمان</a></li>
						  <li><a href="/ads/?bysalary=1">حقوق</a></li>
						</ul>
					  </li>
	  </ol>
	</div>

  </div>

  <div class="row">
	  {% for ad in ads%}
		  <div class="col-sm-4" style="height:380px">
			<div class="panel panel-default text-center">
			<div class="panel-heading">
				<img src="{{MEDIA_URL}}{{ad.logo}}" alt="Image" width="100px" style="margin:auto" class="img-responsive">
			  <strong> شرکت {{ad.employer.name}}</strong>
			</div>
	
			<ul class="list-group">
			  <li class="list-group-item">{{ad.get_category_display}}</li>
			  <li class="list-group-item">{{ad.get_city_display}}</li>
			  <li class="list-group-item">ماهانه {{ad.salary}} تومان </li>
			  <li class="list-group-item">جنسیت : {{ad.get_gender_display}} </li>
			  <li class="list-group-item"><a href="/adss/?id={{ad.id}}"class="btn btn-info">جزئیات بیشتر</a></li>
			</ul>
			</div>          
		  </div>
	  {% endfor %}

  </div> 

</div><!-- /.container -->

<div calss= "row" style="text-align: center">
  <div class="col-lg-12">

  <div class="pagination">
	  <ul class="pager">
  	
  		{% if ads.has_previous %}
  			<li class="previous"><a href="?page={{ ads.previous_page_number }}">&rarr; قدیمی‌تر</a></li>
  		{% else %}
  			<li class="previous disabled"><a href="#">&rarr; قدیمی‌تر</a></li>
  		{% endif %}
  
  		<span class="current">
  			صفحه {{ ads.number }} از {{ ads.paginator.num_pages }}
  		</span>
  
  		{% if ads.has_next %}
  			<li class="next"><a href="?page={{ ads.next_page_number }}">جدید‌تر &larr;</a></li>
  		{% else %}
  			<li class="next disabled"><a href="#">جدید‌تر &larr;</a></li>
  		{% endif %}
 	 </ul>
  </div>
  </div>
  </div>



<!-- <div calss= "row" style="text-align: center">
  <div class="col-lg-12">
	<ul class="pagination">

	  <li><a href="#">&laquo;</a></li>
	  {% for i in range %}
	  <li><a href="pageclick(i)">{{i}}</a></li>
	  {% endfor %}
	  <li><a href="#">&raquo;</a></li>
	</ul>        
  </div>
</div> -->
<script>
	
</script>
{% endblock %}

jobPortal/portal/templates/email.html
<body style="direction:rtl">
	<h4 style="color:cadetblue">کارفرما با مشخصات زیر برای رزومه شما درخواست ارسال کرده است:</h4>
	<ul>
		<li> شرکت {{ad.employer.name}}</li>
		<li>{{ad.get_category_display}}</li>
		<li> حقوق : {{ad.salary}} تومان </li>
		<li>مهارت های لازم : {{ad.required_skills}}</li>
		<li> تعداد افراد لازم : {{ad.number_of_people}} نفر</li>
	</ul>
	<h6>برای اطلاعات بیشتر به حساب کاربری خود وارد شوید.</h6>
	
</body>

jobPortal/portal/templates/emailtoEmployer.html
<body style="direction:rtl">
	<h4 style="color:cadetblue">کارجو با مشخصات زیر برای آگهی شما درخواست ارسال کرده است:</h4>
	<ul>
		<li> نام : {{job_seeker.name}}</li>
		<li>رشته : {{resume.get_category_display}}</li>
		<li> ساکن : {{resume.city}} </li>
		<li>مهارت ها : {{resume.skills}}</li>
		<li> تحصیلات : {{resume.get_education_display}} نفر</li>
	</ul>
	<h6>برای اطلاعات بیشتر به حساب کاربری خود وارد شوید.</h6>

</body>

jobPortal/portal/templates/faq.html
	{% extends 'base.html' %}
    {% block content%}
    <div class="container">
    
    	  <div class="row">
    
    		<div class="col-lg-12">
    		  <h1 class="page-header">سوالات متداول </h1>
    		  <ol class="breadcrumb">
    			<li><a href="index.html">خانه</a></li>
    			<li class="active">سوالات متداول</li>
    		  </ol>
    		</div>
    
    	  </div>
    
    	  <div class="row">
			
    		<div class="col-lg-12">
    
    		  <div class="panel-group" id="accordion">
    			  {% for aq in aqs%}
    			<div class="panel panel-default">
    			  <div class="panel-heading">
    				<h4 class="panel-title">
    				  <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="#collapse{{aq.id}}">
    					{{aq.question}}
    				  </a>
    				</h4>
    			  </div>
    			  <div id="collapse{{aq.id}}" class="panel-collapse collapse">
    				<div class="panel-body">
    				 {{aq.answer}}
    				</div>
    			  </div>
    			</div>
    			{% endfor%}
    		  </div>
    
    		</div>
			
    
    	  </div>
    
    	</div><!-- /.container -->
    

    {% endblock %}

jobPortal/portal/templates/festival_register.html
{% extends 'base.html' %}
{% block content%}

{% if messages %}
	{% for message in messages%}
	<div class="row">
		<div class="col-md-8" style="margin:20px">
	<div class="alert alert-danger">{{message}}</div>			
		</div>
		
	</div>

	{% endfor %}

{% else %}
	<div class="row">
	<div class="col-md-8" style="margin:20px">
			<div class="panel panel-info" style="border:0px">
			<div class="panel-heading">
			  <strong>ثبت نام {{festival.title}}</strong>
			</div>
			<ul class="list-group" >
				 <!--  <li class="list-group-item">{{resume.get_category_display}}</li> -->
				 <li class="list-group-item"><strong>اطلاعات شما: </strong></li>
				  <li class="list-group-item"><strong>نام : </strong>{{employer.name}}</li>
				  <li class="list-group-item"><strong>تلفن :</strong>{{employer.telephone}}</li>
				  <li class="list-group-item"><strong>کد اقتصادی :</strong> {{employer.economic_code}}</li>
				  <li class="list-group-item"><strong> رایانامه :</strong>{{employer.email}}</li>
				  <li class="list-group-item"> <strong>آدرس : </strong>{{employer.address}}</li>
			</ul>
			</div> 
 <a href="/festivals/register/payment/?id={{festival.id}}"><button type="button" class="btn btn-primary" onclick="pardakht()">پرداخت</button></a>
 
 </div>
 </div>
 <style>

{% endif %}

{% endblock %}

jobPortal/portal/templates/festivals.html
{% extends 'base.html' %}
{% block content%}
<div class="container">

  <div class="row">

	<div class="col-md-12">
	  <h1 class="page-header">جشنواره‌ها<small> در مهندسی </small></h1>
	  <ol class="breadcrumb">
		  <li class="dropdown">
						<span class="dropdown-toggle" data-toggle="dropdown">نمایش بر اساس <b class="caret"></b></span>
						<ul class="dropdown-menu">
						  <li><a href="pricing.html">زمان</a></li>
				  <li><a href="pricing.html">مکان</a></li>
						</ul>
				  </li>
	  </ol>
	</div>

  </div>

  <div class="row">
	  {% for f in fes%}
	  <div class="col-md-4">
		<div class="panel panel-default text-center" >
		<div class="panel-heading">
		  <div class="pbl mbl"><a href="#x"><img src="{{MEDIA_URL}}{{f.poster}}" style="margin:auto" width="200px" alt="Image" class="img-responsive"></a>
		</div>

		<ul class="list-group" style="padding-top:15px;list-style-type:none">
		  <li class="list-group-item"><strong> تاریخ شروع: </strong>{{f.from_date}}</li>
		  <li class="list-group-item"><strong> تاریخ پایان: </strong>{{f.to_date}}</li>
		  <li class="list-group-item"><strong> تاریخ پایان: </strong>{{f.discount}} % </li>
		  <li class="list-group-item" style="height:280px"><strong> توضیحات: </strong>{{f.description}}</li>
		  <li style="margin-top:10px"><a  class="btn btn-primary" href="/festivals/register/?id={{f.id}}">ثبت نام کنید</a> </li>
		</ul>
		</div>          
	  </div>
	  </div>
	  {% endfor %}

  </div>

</div><!-- /.container -->
<div calss= "row" style="text-align: center">
  <div class="col-lg-12">

  <div class="pagination">
	  <ul class="pager">

  		{% if ads.has_previous %}
  			<li class="previous"><a href="?page={{ fes.previous_page_number }}">&rarr; قدیمی‌تر</a></li>
  		{% else %}
  			<li class="previous disabled"><a href="#">&rarr; قدیمی‌تر</a></li>
  		{% endif %}

  		<span class="current">
  			صفحه {{ fes.number }} از {{ fes.paginator.num_pages }}
  		</span>

  		{% if ads.has_next %}
  			<li class="next"><a href="?page={{ fes.next_page_number }}">جدید‌تر &larr;</a></li>
  		{% else %}
  			<li class="next disabled"><a href="#">جدید‌تر &larr;</a></li>
  		{% endif %}
 	 </ul>
 		 </div>
 	 </div>
  </div>
{% endblock %}

jobPortal/portal/templates/jobRequests.html
{% extends 'accountBase.html' %}
{% load staticfiles %}
{% block Account %}
{% if mod == 'a' %}
<h1 class="page-header">درخواست هایی که داده اید</h1>
{% elif mod == 'b' %}
<h1 class="page-header">پیشنهادهایی که به شما داده شده</h1>
{% elif mod == 'd' %}
<h1 class="page-header">نتایج موفق</h1>
{% else %}
<h1 class="page-header">پیشنهادهای سیستم</h1>
{% endif %}
 <div class="row">
 	  {% for ad in result%}


 			<ul class="list-group">
	 		{% if mod != 'c' and ad.success == 'F' %}
	 		<li class="label label-danger">درخواست ناموفق</li>
	 		{% elif mod != 'c' and ad.success == 'T' %}
	 		<li class="label label-success">درخواست موفق</li>
			{% elif mod == 'c' and ad.advertisement.state == "D" %}
			<li class="label label-warning">این آگهی غیر فعال شده است</li>
			{% elif mod == 'c' and ad.advertisement.state == "A" %}
			<li class="label label-primary">این آگهی فعال است</li>

	 		{% else %}
	 		<li class="label label-info">درخواست معلق</li>

	 		{% endif %}
 			  <li class="list-group-item">{{ad.advertisement.get_category_display}}</li>
 			  <li class="list-group-item">شهر : {{ad.advertisement.get_city_display}}</li>
 			  <li class="list-group-item">حقوق پیشنهادی : {{ad.advertisement.salary}}</li>

 			  <li class="list-group-item">جنسیت : {{ad.advertisement.get_gender_display}} </li>
 			</ul>

 	 <a class="btn btn-primary" href="/adss/?id={{ad.advertisement.id}}"> مشاهده کامل آگهی <i class="fa fa-angle-left"></i></a>
 	 {% if mod == 'b' and ad.success = 'P' %}
 	 <a class="btn btn-primary" href="/accreq/{{ad.id}}"> پذیرش درخواست <i class="fa fa-angle-left"></i></a>
<a class="btn btn-primary" href="/rejreq/{{ad.id}}"> رد درخواست <i class="fa fa-angle-left"></i></a>

 	 {% endif %}
 	 

 	
 	<hr>
 {% endfor %}
   </div>

 {% endblock %}

jobPortal/portal/templates/userAd.html
{% extends 'accountBase.html' %}
{% load staticfiles %}
{% block Account %}



<h1 class="page-header">آگهی هایی که ثبت کرده اید</h1>

 <div class="row">
	 {% for sad in sads %}
		<ul class="list-group">
			<span class="label label-warning" >ویژه </span>
			{% if sad.advertisement.state == "D" %}
			<li class="label label-warning">این آگهی غیر فعال شده است</li>
			{% elif sad.advertisement.state == "A" %}
			<li class="label label-primary">این آگهی فعال است</li>
			{% endif %}

		  <li class="list-group-item">{{sad.advertisement.get_category_display}}</li>
		  <li class="list-group-item">شهر : {{sad.advertisement.get_city_display}}</li>
		  <li class="list-group-item">حقوق پیشنهادی : {{sad.advertisement.salary}}</li>

		  <li class="list-group-item">جنسیت : {{sad.advertisement.get_gender_display}} </li>
		</ul>

 <a class="btn btn-primary" href="/adss/?id={{sad.advertisement.id}}"> مشاهده کامل آگهی <i class="fa fa-angle-left"></i></a>
 <a class="btn btn-primary" href="/updateAd/{{sad.advertisement.id}}/"> تغییر آگهی <i class="fa fa-angle-left"></i></a>
 {% if sad.advertisement.state == "A" %}

 <a class="btn btn-primary" href="/removeAd/{{sad.advertisement.id}}/"> غیر فعال کردن آگهی <i class="fa fa-angle-left"></i></a>
 {% endif %}
<hr>
{% endfor %}
	 
	{% for ad in ads%}


	<ul class="list-group">
		{% if ad.state == "D" %}
		<li class="label label-warning">این آگهی غیر فعال شده است</li>
		{% elif ad.state == "A" %}
		<li class="label label-primary">این آگهی فعال است</li>
		{% endif %}

	  <li class="list-group-item">{{ad.get_category_display}}</li>
	  <li class="list-group-item">شهر : {{ad.get_city_display}}</li>
	  <li class="list-group-item">حقوق پیشنهادی : {{ad.salary}}</li>

	  <li class="list-group-item">جنسیت : {{ad.get_gender_display}} </li>
	</ul>

	<a class="btn btn-primary" href="/adss/?id={{ad.id}}"> مشاهده کامل آگهی <i class="fa fa-angle-left"></i></a>
	<a class="btn btn-primary" href="/updateAd/{{ad.id}}/"> تغییر آگهی <i class="fa fa-angle-left"></i></a>
	{% if ad.state == "A" %}

	<a class="btn btn-primary" href="/removeAd/{{ad.id}}/"> غیر فعال کردن آگهی <i class="fa fa-angle-left"></i></a>
	{% endif %}

	<a class="btn btn-primary" href="/special_ad_register/{{ad.id}}"> ویژه کردن آگهی <i class="fa fa-angle-left"></i></a>


	<hr>

	{% endfor %}
   </div>

 {% endblock %}